<a href="https://colab.research.google.com/github/ktb5891/BigDataAnalysisEngineer/blob/main/BigDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# 작업형 유형 1 문제(1)

In [7]:
# 데이터 정렬과 평균치 산출

In [6]:
# alcohol(음주수치)이 상위 10번째 값으로 상위 1~10위의 범위의 값을 변경한 후
# speeding(속도)가 7이상의 alcohol(음주수치)데이터들의 평균 산출
# 최종 결과만 print 출력

In [12]:
# data 불러오기
import seaborn as sns
import pandas as pd
sns.get_dataset_names()
df = sns.load_dataset('car_crashes')
print(df.head())

   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA  


In [10]:
data = df.sort_values(by = df.columns[2], ascending = False) # alcohol을 기준으로 내림차순 정렬
# data.head()
ten = data.iloc[9,2] # alcohol의 10번째 값
data.iloc[:10,2] = ten # 1~10위까지의 alcohol 값 변경
# data.head(11)
result = data[(data['speeding'] >= 7)] # speeding이 7 이상인 값
print('최종 결과물 : ', result['alcohol'].mean()) # 평균값 도출

최종 결과물 :  5.600099999999999


In [13]:
# 작업형 유형 1문제 (2)

In [14]:
# 특정 비율만큼의 데이터와 결측치 대체, 전처리 전 후 표준편차 비교

In [15]:
# 데이터 첫번째 행부터 70%까지의 데이터를 추출한 후
# distance(거리)의 결측값을 distance(거리)의 중앙값으로 대체하고
# 결측값 전처리 전과 후의 표준편차를 비교
# 전/후 결과값 print 출력

In [50]:
# 데이터 불러오기
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('planets')
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [51]:
length = int(len(df)*0.7) 
df = df[:length] # 70% 데이터 추출

In [52]:
df2 = df.copy() 
df2['distance'] = df2['distance'].fillna(df2['distance'].median()) # 결측치를 중앙값으로 대체
df2

method  number  orbital_period   mass  distance  year
0    Radial Velocity       1      269.300000   7.10     77.40  2006
1    Radial Velocity       1      874.774000   2.21     56.95  2008
2    Radial Velocity       1      763.000000   2.60     19.84  2011
3    Radial Velocity       1      326.030000  19.40    110.62  2007
4    Radial Velocity       1      516.220000  10.50    119.47  2009
..               ...     ...             ...    ...       ...   ...
719          Transit       1      131.458000    NaN   1645.00  2011
720          Transit       2       13.839890    NaN    470.00  2012
721          Transit       2       16.238550    NaN    470.00  2012
722          Transit       3       13.367308    NaN     66.00  2013
723          Transit       3       21.301886    NaN     66.00  2013

[724 rows x 6 columns]

In [53]:
print('전처리 전 distance 표준편차: ',np.std(df['distance']))
print('전처리 후 distance 표준편차: ',np.std(df2['distance']))

전처리 전 distance 표준편차:  275.0161144074897
전처리 후 distance 표준편차:  267.05138442597666


In [54]:
# 작업형 유형 1문제 (3)

In [55]:
# 통계 기법(IQR) 방식의 이상치 제거

In [56]:
# orbital_period열의 이상치를 IQR 기법으로 제거하여
# 이상치들의 합을 계산
# 최종 결과만 print 출력

In [58]:
# 데이터 불러오기

import seaborn as sns
sns.get_dataset_names()
df = sns.load_dataset('planets')
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [59]:
q25 = df['orbital_period'].quantile(0.25) # orbital_period의 1사분위 값
q75 = df['orbital_period'].quantile(0.75) # orbital_period의 3사분위 값
iqr = q75-q25 # iqr의 범위
print(q25, q75, iqr)

5.4425405 526.005 520.5624595


In [65]:
min = q25-iqr*1.5 # 이상치를 제거한 최소 값
max = q75+iqr*1.5 # 이상치를 제거한 최대 값
print(min,max)

-775.4011487500002 1306.84868925


In [67]:
df_outlier = df[(df['orbital_period'] <= min) | (df['orbital_period'] >= max)] # 이상치를 제거한 df
print(df_outlier['orbital_period'].sum())

1818772.582


In [68]:
# 작업유형 2 수집 및 전처리

In [69]:
# 데이터 불러오기

import seaborn as sns
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [71]:
# 데이터 결측치 보정

missing = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
for i in missing:
    df[i] = df[i].fillna(df[i].median())
df['sex'] = df['sex'].fillna('Male')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen           39.10           18.7              181.0   
1  Adelie  Torgersen           39.50           17.4              186.0   
2  Adelie  Torgersen           40.30           18.0              195.0   
3  Adelie  Torgersen           44.45           17.3              197.0   
4  Adelie  Torgersen           36.70           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3       4050.0    Male  
4       3450.0  Female

In [72]:
# 라벨 인코딩

label = ['species','island','sex']
from sklearn.preprocessing import LabelEncoder
df[label] = df[label].apply(LabelEncoder().fit_transform)
df

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0          0       2           39.10           18.7              181.0   
1          0       2           39.50           17.4              186.0   
2          0       2           40.30           18.0              195.0   
3          0       2           44.45           17.3              197.0   
4          0       2           36.70           19.3              193.0   
..       ...     ...             ...            ...                ...   
339        2       0           44.45           17.3              197.0   
340        2       0           46.80           14.3              215.0   
341        2       0           50.40           15.7              222.0   
342        2       0           45.20           14.8              212.0   
343        2       0           49.90           16.1              213.0   

     body_mass_g  sex  
0         3750.0    1  
1         3800.0    0  
2         3250.0    0  
3         4050.0    1  
4         3450.0    0  
..           ...  ...  
339       4050.0    1  
340       4850.0    0  
341       5750.0    1  
342       5200.0    0  
343       5400.0    1  

[344 rows x 7 columns]

In [73]:
# 데이터 타입, 더미 변환

import pandas as pd
category = ['island','sex']
for i in category:
    df[i] = df[i].astype('category')
df = pd.get_dummies(df)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  
0         0         0         1      0      1  
1         0         0         1      1      0  
2         0         0         1      1      0  
3         0         0         1      0      1  
4         0         0         1      1      0

In [75]:
# 파생변수 생성

df['body_mass_g_qcut'] = pd.qcut(df['body_mass_g'], 5, labels = False)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

In [76]:
# 정규화 또는 스케일 작업

from sklearn.preprocessing import MinMaxScaler
scaler = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
min = MinMaxScaler()
min.fit(df[scaler])
df[scaler] = min.transform(df[scaler])
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0        0.254545       0.666667           0.152542     0.291667   
1        0        0.269091       0.511905           0.237288     0.305556   
2        0        0.298182       0.583333           0.389831     0.152778   
3        0        0.449091       0.500000           0.423729     0.375000   
4        0        0.167273       0.738095           0.355932     0.208333   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

In [79]:
# 데이터 분리

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df['species'], test_size = 0.2, stratify = df['species'], random_state = 1)
print(X_train, X_test, y_train, y_test)

     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  island_0  \
193        0.512727       0.523810           0.254237     0.263889         0   
98         0.036364       0.357143           0.101695     0.055556         0   
155        0.483636       0.666667           0.271186     0.229167         0   
40         0.160000       0.583333           0.169492     0.125000         0   
281        0.512727       0.214286           0.830508     0.722222         1   
..              ...            ...                ...          ...       ...   
176        0.530909       0.571429           0.389831     0.166667         0   
39         0.280000       0.714286           0.203390     0.541667         0   
245        0.509091       0.238095           0.728814     0.666667         1   
196        0.683636       0.571429           0.406780     0.270833         0   
188        0.563636       0.619048           0.389831     0.319444         0   

     island_1  island_2  sex_0  sex_1  

In [81]:
# 모형 학습(1)

from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier(max_depth = 6, n_estimators = 100)
model1.fit(X_train, y_train)
pred1 = model1.predict(X_test)
pred1

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [83]:
# 모형 학습(2)

from sklearn.ensemble import AdaBoostClassifier
model2 = AdaBoostClassifier()
model2.fit(X_train, y_train)
pred2 = model2.predict(X_test)
pred2

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [84]:
# 앙상블

from sklearn.ensemble import VotingClassifier
clf = VotingClassifier(estimators = [('rf',model1), ('ad',model2)], voting = 'hard')
clf.fit(X_train, y_train)
pred3 = clf.predict(X_test)
pred3

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [86]:
# 모델 평가

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print('랜덤 포레스트 정확도 : ', accuracy_score(y_test, pred1))
print('아이다 부스트 정확도 : ', accuracy_score(y_test, pred2))
print('앙상블(랜포+아이다) 보팅 정확도 : ', accuracy_score(y_test, pred3))


랜덤 포레스트 정확도 :  1.0
아이다 부스트 정확도 :  0.9855072463768116
앙상블(랜포+아이다) 보팅 정확도 :  1.0


In [88]:
# 하이퍼 파라미터 튜닝

from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[50,100], 'max_depth':[4,6]}
model4 = RandomForestClassifier()
clf = GridSearchCV(estimator = model4, param_grid = parameters, cv = 3)
clf.fit(X_train,y_train)
print('최적의 파라미터 : ', clf.best_params_)

최적의 파라미터 :  {'max_depth': 6, 'n_estimators': 100}


In [89]:
# 저장 및 답안 제출

pd.DataFrame({'id':y_test.index, 'pred':pred3}).to_csv('202205111324.csv',index = False)
check = pd.read_csv('202205111324.csv')
check.head()

id  pred
0   57     0
1  173     1
2  213     1
3   50     0
4   25     0